Support up to GKI v5.10 kernels (#1)
* kernel: fix drm_helper_mode_fill_fb_struct() for 4.11+

Adapt to a3f913ca9892 ("drm: Pass 'dev' to
drm_helper_mode_fill_fb_struct()") upstream

* kernel: fix gamma_set() for 4.12+

Adapt to 6d124ff84533 ("drm: Add acquire ctx to ->gamma_set hook")
upstream

* kernel: fix crtc_enable() for 4.14+ & <5.11

Adapt to 0b20a0f8c3cb ("drm: Add old state pointer to CRTC .enable()
helper function"), 351f950db4ab ("drm/atomic: Pass the full state to
CRTC atomic enable/disable") & f6ebe9f9c923 ("drm/atomic: Pass the full
state to CRTC atomic begin and flush") upstream

* kernel: drop DRIVER_PRIME for 5.4+

Adapt to 0424fdaf883a ("drm/prime: Actually remove DRIVER_PRIME
everywhere") upstream

* kernel: rename membrane_probe()'s "drm" struct drm_device* to "dev"

In preparation of the 5.10 support changes, otherwise they FTBFS with:

  .../drivers/membrane/membrane_drv.c:300:12: error: no member named 'drm' in 'membrane_device'
      mdev = devm_drm_dev_alloc(&pdev->dev, &membrane_driver, typeof(*mdev), drm);
             ^                                                               ~~~
  .../include/drm/drm_drv.h:632:12: note: expanded from macro 'devm_drm_dev_alloc'
                                         offsetof(type, member)))
                                         ^              ~~~~~~
  .../include/linux/stddef.h:17:32: note: expanded from macro 'offsetof'
  #define offsetof(TYPE, MEMBER)  __compiler_offsetof(TYPE, MEMBER)
                                  ^                         ~~~~~~
  .../include/linux/compiler_types.h:135:35: note: expanded from macro '__compiler_offsetof'
  #define __compiler_offsetof(a, b)       __builtin_offsetof(a, b)
                                          ^                     ~

* kernel: drop drm_dev_init() for 5.10+

Adapt to a7d39439f8bd ("drm/dev: Remove drm_dev_init") based on
df2ce4596c04 ("drm/amdgpu: Convert to using devm_drm_dev_alloc() (v2)")
upstream